"""empty message

Revision ID: 0249043caed5
Revises: ff9f5042cbc0
Create Date: 2022-09-08 22:28:17.310701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0249043caed5'
down_revision = 'ff9f5042cbc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_Barcode_product_name_Ingredient', 'Barcode', type_='foreignkey')
    op.drop_column('Barcode', 'expiry_date')
    op.drop_column('Recipe_ingredient', 'ingredient_id')
    op.create_foreign_key(op.f('fk_Recipe_situation_recipe_id_Recipes'), 'Recipe_situation', 'Recipes', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Recipe_situation_recipe_id_Recipes'), 'Recipe_situation', type_='foreignkey')
    op.add_column('Recipe_ingredient', sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Barcode', sa.Column('expiry_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_Barcode_product_name_Ingredient', 'Barcode', 'Ingredient', ['product_name'], ['ingredient_name'])
    # ### end Alembic commands ###
