"""empty message

Revision ID: 0480a62fddc4
Revises: bb707c3d7c44
Create Date: 2022-09-08 21:27:43.360283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0480a62fddc4'
down_revision = 'bb707c3d7c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=False),
    sa.Column('press', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Article'))
    )
    op.create_table('Situation',
    sa.Column('situation_id', sa.Integer(), nullable=False),
    sa.Column('situation_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['situation_id'], ['Recipe_situation.situation_id'], name=op.f('fk_Situation_situation_id_Recipe_situation')),
    sa.PrimaryKeyConstraint('situation_id', name=op.f('pk_Situation'))
    )
    op.drop_table('situation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situation',
    sa.Column('situation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('situation_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['situation_id'], ['Recipe_situation.situation_id'], name='fk_situation_situation_id_Recipe_situation'),
    sa.PrimaryKeyConstraint('situation_id', name='pk_situation')
    )
    op.drop_table('Situation')
    op.drop_table('Article')
    # ### end Alembic commands ###
