"""empty message

Revision ID: 1bb7c914e681
Revises: 6e7f47b3af47
Create Date: 2022-09-08 08:30:33.013111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb7c914e681'
down_revision = '6e7f47b3af47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridge', sa.Column('product_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fridge', 'product_id')
    # ### end Alembic commands ###
