"""empty message

Revision ID: 3c2714f1e251
Revises: da41c8e72388
Create Date: 2022-09-08 04:37:47.902845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c2714f1e251'
down_revision = 'da41c8e72388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fridge',
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.Integer(), nullable=True),
    sa.Column('subclass', sa.String(length=150), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('old_exp_date', sa.Date(), nullable=False),
    sa.Column('new_exp_date', sa.Date(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_fridge_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product', name=op.f('pk_fridge'))
    )
    op.alter_column('user', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("'2022-09-25 19:27:35.508'::timestamp without time zone"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'create_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("'2022-09-25 19:27:35.508'::timestamp without time zone"))
    op.drop_table('fridge')
    # ### end Alembic commands ###
