"""empty message

Revision ID: 43110ca974b1
Revises: 19b71b08abde
Create Date: 2022-09-06 01:49:37.177024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43110ca974b1'
down_revision = '19b71b08abde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
    op.create_foreign_key(op.f('fk_question_user_id_user'), 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_question_user_id_user'), 'question', type_='foreignkey')
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###
