"""empty message

Revision ID: 4d5a5a514644
Revises: e074a64dae0b
Create Date: 2022-09-08 11:29:03.733425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d5a5a514644'
down_revision = 'e074a64dae0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barcode')
    op.add_column('fridge', sa.Column('adding_date', sa.DateTime(), nullable=True))
    op.drop_column('fridge', 'create_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridge', sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('fridge', 'adding_date')
    op.create_table('barcode',
    sa.Column('barcode_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('barcode_id', name='pk_barcode')
    )
    # ### end Alembic commands ###
