"""empty message

Revision ID: 5ba7d6a714e2
Revises: 1bb7c914e681
Create Date: 2022-09-08 08:32:52.215173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba7d6a714e2'
down_revision = '1bb7c914e681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridge', sa.Column('product_id', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fridge', 'product_id')
    # ### end Alembic commands ###
