"""empty message

Revision ID: 6512b9c647b3
Revises: c9098b569fd1
Create Date: 2022-09-08 03:12:56.379425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6512b9c647b3'
down_revision = 'c9098b569fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=100), nullable=True, sever_default='F'))
    op.add_column('user', sa.Column('region', sa.String(length=200), nullable=True, sever_default='부천'))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True, sever_default='29'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    op.drop_column('user', 'region')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
