"""empty message

Revision ID: c9098b569fd1
Revises: 2eec8d682c75
Create Date: 2022-09-06 02:17:14.403255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9098b569fd1'
down_revision = '2eec8d682c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.add_column('question', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'modify_date')
    op.drop_column('answer', 'modify_date')
    # ### end Alembic commands ###
