"""empty message

Revision ID: cc901481b762
Revises: 449e8a989fea
Create Date: 2022-09-08 03:31:14.509576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc901481b762'
down_revision = '449e8a989fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'region',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'region',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
