"""empty message

Revision ID: d8206fca08a8
Revises: f7c4459fbd35
Create Date: 2022-09-08 21:49:29.379266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8206fca08a8'
down_revision = 'f7c4459fbd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Article', 'link')
    op.drop_column('Article', 'dsc')
    op.create_foreign_key(op.f('fk_Barcode_product_name_Ingredient'), 'Barcode', 'Ingredient', ['product_name'], ['ingredient_name'])
    op.drop_column('Barcode', 'expiry_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Barcode', sa.Column('expiry_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_Barcode_product_name_Ingredient'), 'Barcode', type_='foreignkey')
    op.add_column('Article', sa.Column('dsc', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('Article', sa.Column('link', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
