"""empty message

Revision ID: da41c8e72388
Revises: 764dcb165d05
Create Date: 2022-09-08 03:41:55.872722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da41c8e72388'
down_revision = '764dcb165d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_date', sa.DateTime(), server_default='2022-09-25 19:27:35.508', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_date')
    # ### end Alembic commands ###
