"""empty message

Revision ID: e074a64dae0b
Revises: aa37ed7bd6f7
Create Date: 2022-09-08 11:18:08.196328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e074a64dae0b'
down_revision = 'aa37ed7bd6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barcode')
    op.add_column('fridge', sa.Column('exp_date', sa.Date(), nullable=False))
    op.add_column('fridge', sa.Column('adding_date', sa.DateTime(), nullable=True))
    op.drop_column('fridge', 'create_date')
    op.drop_column('fridge', 'new_exp_date')
    op.drop_column('fridge', 'old_exp_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fridge', sa.Column('old_exp_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('fridge', sa.Column('new_exp_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('fridge', sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('fridge', 'adding_date')
    op.drop_column('fridge', 'exp_date')
    op.create_table('barcode',
    sa.Column('barcode_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('barcode_id', name='pk_barcode')
    )
    # ### end Alembic commands ###
