"""empty message

Revision ID: f7c4459fbd35
Revises: 0480a62fddc4
Create Date: 2022-09-08 21:33:44.678270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c4459fbd35'
down_revision = '0480a62fddc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Article', 'posted_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('Article', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('Article', 'posted_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
