"""empty message

Revision ID: ff9f5042cbc0
Revises: d8206fca08a8
Create Date: 2022-09-08 22:06:59.972215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9f5042cbc0'
down_revision = 'd8206fca08a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Article', sa.Column('dsc', sa.String(length=500), nullable=True))
    op.add_column('Article', sa.Column('link', sa.String(length=200), nullable=True))
    op.add_column('Barcode', sa.Column('exp_days', sa.Integer(), nullable=True))
    op.drop_column('Barcode', 'expiry_date')
    op.alter_column('Recipes', 'recipe_desc',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Recipes', 'recipe_desc',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.add_column('Barcode', sa.Column('expiry_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Barcode', 'exp_days')
    op.drop_column('Article', 'link')
    op.drop_column('Article', 'dsc')
    # ### end Alembic commands ###
